---
- name: Playbook to deal with secrets
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  collections:
    - kubernetes.core
    
  tasks:
    - name: Add a secret to Kubernetes default
      kubernetes.core.k8s:
        state: absent
        definition:
          apiVersion: v1
          kind: Secret
          type: Opaque
          metadata:
            name: my-secret
            namespace: default
          data:
            username: "{{ username | b64encode }}"
            password: "{{ password | b64encode }}"
      register: secret
      
    - name: Debug secret
      ansible.builtin.debug:
        var: secret
