---
- name: Playbook to deal with secrets
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  collections:
    - kubernetes.core
    
  tasks:
    - name: Add a secret to Kubernetes default
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          type: Opaque
          metadata:
            name: my-secret
            namespace: default
          data:
            username: "{{ username }}"
            password: "{{ password }}"
      register: secret
