---
- name: Playbook to deal with secrets
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  vars:
    version: "v0.18.0"
  collections:
    - kubernetes.core
    
  tasks:
    - name: Add a secret to Kubernetes default
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          type: Opaque
          metadata:
            name: my-secret
            namespace: default
          data:
            username: "{{ username | b64encode }}"
            password: "{{ password | b64encode }}"
      register: secret
      
    - name: Debug secret
      ansible.builtin.debug:
        var: secret
        
    - name: Download controller yaml
      ansible.builtin.get_url: 
        url: "https://github.com/bitnami-labs/sealed-secrets/releases/download/{{ version }}/controller.yaml"
        dest: "./controller.yaml"
        
    - name: Apply controller to environment
      kubernetes.core.k8s:
        state: present
        src: "./controller.yaml"
        
    - name: Download kubeseal
      ansible.builtin.get_url:
        url: "https://github.com/bitnami-labs/sealed-secrets/releases/download/{{ version }}/kubeseal-linux-amd64"
        dest: "/usr/local/bin"
        mode: '0755'
      become: yes

    - name: Rename kubeseal
      copy: 
        src: "/usr/local/bin/kubeseal-linux-amd64"
        dest: "/usr/local/bin/kubeseal" 
        remote_src: yes
      become: yes

    - name: command:
      command: "/usr/local/bin/kubeseal --help"
    
